name: Build RTCore

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v2.3.1
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Generate & Build Project
        run: |
             cmake -Bbuild .
             cmake --build ./build --config Release
        shell: cmd
      - name: Run Unit Tests
        run: |
             ./bin/RTCore.exe --unittest
        shell: powershell
  Macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v2.3.1
      - name: Generate & Build Project
        run: |
             cmake -Bbuild .
             cmake --build ./build --config Release
      - name: Run Unit Tests
        run: |
             ./bin/RTCore --unittest
  Ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v2.3.1
      - name: Generate & Build Project
        run: |
             cmake -Bbuild .
             cmake --build ./build --config Release
        env:
         CC:   gcc-10
         CXX:  g++-10
      - name: Run Unit Tests
        run: |
             ./bin/RTCore --unittest
        
